### ISSUE TITLE
Inquiry: Future Plans [ASP.NET Core support]

### ISSUE THREAD

**Issue by BrooksV** [VahidN/DNTBreadCrumb#2]
Hi Vahid,

I'm working on a creating a project (DNX, MVC6, Asp.Net One, etc...) and have been looking for a clean way to implement BreadCrumbs without the need to resort to MvcSiteMaps. Your DNTBreadCrumb approach seems to be the approach I was looking for.

I would have used the BootStrap approach but that requires the BreadCrumbs to be included as content in the View where as I want the BreadCrumb in the header (_Layout.chtml) above the navigation menu.

What are your future plans for supporting MVC6 and Asp.Net One? Will you be updating DNTBreadCrumb anytime soon?

Best Regards,
Brooks

**Comment by VahidN** [comment]
Added ASP.NET Core support:
[https://github.com/VahidN/DNTBreadCrumb.Core](https://github.com/VahidN/DNTBreadCrumb.Core)
